name: T-PicoC3 CI

on:
  push:
    paths:
      - 'target/rp2/boards/LILYGO_T_PicoC3/**'
      - 'target/rp2/rp2.mk'
      - '.github/workflows/t-picoc3.yml'
  pull_request:
    paths:
      - 'target/rp2/boards/LILYGO_T_PicoC3/**'
      - 'target/rp2/rp2.mk'
      - '.github/workflows/t-picoc3.yml'

jobs:
  build_t-picoc3:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Cache dl
      id: cache-dl
      uses: actions/cache@v3
      with:
        path: dl/
        key: ${{ runner.os }}-${{ hashFiles('**/dl') }}
    - name: Install packages
      run: sudo apt-get install git make python3 python3-pip cmake quilt
    - name: Build T-PicoC3
      run: |
        cp config_T-PicoC3 config
        sudo apt install gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential
        make
    - name: Deliver firmware
      uses: actions/upload-artifact@v3
      with:
        name: LILYGO_T_PicoC3_firmware
        path: ./bin/rp2/LILYGO_T_PicoC3/