name: T-RGB CI

on:
  push:
    paths:
      - 'target/esp32s3/boards/LILYGO_T-/**'
      - 'target/esp32s3/esp32s3.mk'
      - '.github/workflows/t-displays3.yml'
  pull_request:
    paths:
      - 'target/esp32s3/boards/LILYGO_T-RGB/**'
      - 'target/esp32s3/esp32s3.mk'
      - '.github/workflows/t-displays3.yml'

jobs:
  build_t-rgb:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Cache dl
      id: cache-dl
      uses: actions/cache@v3
      with:
        path: dl/
        key: ${{ runner.os }}-${{ hashFiles('**/dl') }}
    - name: Install packages
      run: sudo apt-get install git make python3 python3-pip cmake quilt
    - name: Build T-RGB
      run: |
        cp config_T-RGB config
        make
    - name: Deliver firmware
      uses: actions/upload-artifact@v3
      with:
        name: LILYGO_T-RGB_firmware
        path: ./bin/esp32s3/LILYGO_T-RGB/